schema: spec-driven
created: "2026-06-26"
tags:
    type: fullstack
    complexity: 3
    components:
        - kanban-board
        - change-status
        - api-router
    _auto: true
    _tagged_at: "2026-06-30"
